### PR TITLE
feat: support `npm publish` with correct `publishConfig#registry` in `package.json`

### LINKED ISSUE #1271: [feat] `@changesets/cli` Ability to publish on different registries at once
## Affected Packages

`@changesets/cli`

## Problem

https://github.com/npm/cli/issues/7043#issuecomment-1839051764

## Proposed solution

Run `npm publish` with `--registry` if `publishConfig#registry` defined in `package.json`

### PR DESCRIPTION
**Pull request by JounQin**
close #1271

### CODE REVIEW

**Comment by JounQin** [comment]
It seems the current implementation is not enough, in our case, we have `@sope:registry=//xxx` in project level `.npmrc`, `npm publish --registry` is not enough, we'll have to use `npm publish --@sope:registry` to override...

**Comment by sambacha** [comment]
> It seems the current implementation is not enough, in our case, we have `@sope:registry=//xxx` in project level `.npmrc`, `npm publish --registry` is not enough, we'll have to use `npm publish --@sope:registry` to override, and we need to adapt `npm info` with correct registry accordingly...

you have to use --"@scope:registry=registryURL", not --registry=registryURL

setting `publishConfig` in your manifest will override `.npmrc` 
```json
"publishConfig": {
    "@OrgScope:registry": "registry-URL"
  }
```

**Comment by JounQin** [comment]
@sambacha Thanks for your advice! Is there any reference of `@scope:registry` of `publishConfig` field in `package.json`?

**Comment by JounQin** [comment]
https://github.com/npm/cli/issues/7043#issuecomment-2341303856

**Pull request closed without merging**
