### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by janosh**
Noticed a few typos across the code base while doing #677.

### CODE REVIEW

**Comment by janosh** [comment]
@Andarist Could you take a quick look? Not much to review here I think.

**Comment by Andarist** [comment]
@janosh the changes look good to me, thank you for that. There are some merge conflicts and I can't merge it right now - this could have been caused by my recent merges to the main branch, sorry for that. Would you be able to resolve those conflicts?

**Comment by janosh** [comment]
@Andarist All conflicts resolved. Would be cool if this could be merged soon since it does affect 20 files so more conflicts are likely.

**Comment by Andarist** [comment]
Thank you for that ❤️

**Pull request merged**
